 export const JsSidebarOptions :string[] = [
  "JS Tutorial",
  "JS Syntax",
  "JS Variables",
  "JS Operators",
  "JS If Conditions",
  "JS Loops",
  "JS Strings",
  "JS Numbers",
  "JS Functions",
  "JS Objects",
  "JS Dates",
  "JS Arrays",
  "JS Sets",
  "JS Maps",
  "JS Math",
  "JS RegExp",
  "JS Data Types",
  "JS Errors",
  "JS Debugging",
  "JS Events",
  "JS Programming",
  "JS References",
  "JS UTF-8 Characters",
  "JS Advanced",
  "JS Versions",
  "JS Functions",
  "JS Objects",
  "JS Classes",
  "JS Iterations",
  "JS Promises",
  "JS Modules",
  "JS HTML DOM",
  "JS Windows",
  "JS Web API",
  "JS AJAX",
  "JS JSON",
  "JS jQuery",
  "JS Graphics",
  "JS Examples",
  "JS Objects",
];

export const HtmlSidebarOptions :string[] = [
  
"HTML HOME",
"HTML Introduction",
"HTML Editors",
"HTML Basic",
"HTML Elements",
"HTML Attributes",
"HTML Headings",
"HTML Paragraphs",
"HTML Styles",
"HTML Formatting",
"HTML Quotations",
"HTML Comments",
"HTML Colors",
"HTML CSS",
"HTML Links",
"HTML Images",
"HTML Favicon",
"HTML Page Title",
"HTML Tables",
"HTML Lists",
"HTML Block & Inline",
"HTML Div",
"HTML Classes",
"HTML Id",
"HTML Iframes",
"HTML JavaScript",
"HTML File Paths",
"HTML Head",
"HTML Layout",
"HTML Responsive",
"HTML Computercode",
"HTML Semantics",
"HTML Style Guide",
"HTML Entities",
"HTML Symbols",
"HTML Emojis",
"HTML Charsets",
"HTML URL Encode",
"HTML vs. XHTML",

"HTML Forms",
"HTML Forms",
"HTML Form Attributes",
"HTML Form Elements",
"HTML Input Types",
"HTML Input Attributes",

"HTML Graphics",
"HTML Canvas",
"HTML SVG",

"HTML Media",
"HTML Media",
"HTML Video",
"HTML Audio",
"HTML Plug-ins",
"HTML YouTube",

"HTML APIs",
"HTML Web APIs",
"HTML Geolocation",
"HTML Drag and Drop",
"HTML Web Storage",
"HTML Web Workers",
"HTML SSE",

"HTML Examples",
"HTML Examples",
"HTML Editor",
"HTML Quiz",
"HTML Exercises",
"HTML Website",
"HTML Syllabus",
"HTML Study Plan",
"HTML Interview Prep",
"HTML Bootcamp",
"HTML Certificate",
"HTML Summary",
"HTML Accessibility",

"HTML References",
"HTML Tag List",
"HTML Attributes",
"HTML Global Attributes",
"HTML Browser Support",
"HTML Events",
"HTML Colors",
"HTML Canvas",
"HTML Audio/Video",
"HTML Doctypes",
"HTML Character Sets",
"HTML URL Encode",
"HTML Lang Codes",

]

export const ReactSidebarOptions :string[] = [
  
"React Home",
"React Intro",
"React Get Started",
"React First App",
"React Render HTML",
"React Upgrade",
"React ES6",
"React JSX Intro",
"React JSX Expressions",
"React JSX Attributes",
"React JSX If Statements",
"React Components",
"React Class",
"React Props",
"React Props Destructuring",
"React Props Children",
"React Events",
"React Conditionals",
"React Lists",
"React Forms",
"React Forms Submit",
"React Textarea",
"React Select",
"React Multiple Inputs",
"React Checkbox",
"React Radio",
"React Portals",
"React Suspense",
"React CSS Styling",
"React CSS Modules",
"React CSS-in-JS",
"React Router",
"React Transitions",
"React Forward Ref",
"React HOC",
"React Sass",

"React Hooks",

"React useState",
"React useEffect",
"React useContext",
"React useRef",
"React useReducer",
"React useCallback",
"React useMemo",
"React Custom Hooks",

]